export const STRINGS = {
  app: { nome: 'GymFishes' },
  auth: {
    entrar: 'Entrar',
    criarConta: 'Criar conta',
    email: 'E-mail',
    senha: 'Senha',
    emailInvalido: 'E-mail inválido',
    senhaCurta: 'A senha precisa de pelo menos 8 caracteres',
    credenciaisInvalidas: 'E-mail ou senha incorretos',
    falhaRede: 'Falha de conexão. Tente de novo.',
    jaTenhoConta: 'Já tenho conta',
    naoTenhoConta: 'Ainda não tenho conta',
    sair: 'Sair',
  },
  onboarding: {
    tituloNome: 'Como você quer aparecer?',
    campoNome: 'Seu nome',
    nomeCurto: 'Use pelo menos 2 caracteres',
    nomeLongo: 'Use no máximo 20 caracteres',
    tituloGrupo: 'Vocês competem em grupo',
    criarGrupo: 'Criar grupo',
    entrarComCodigo: 'Entrar com código',
    campoGrupo: 'Nome do grupo',
    campoCodigo: 'Código do convite',
    codigoInvalido: 'Código inválido',
    continuar: 'Continuar',
  },
  grupo: {
    codigoDoConvite: 'Código do convite',
    codigoFalhou: 'Não foi possível gerar um código. Tente de novo.',
    copiarCodigo: 'Copiar código',
    copiado: 'Copiado!',
    mostreEsteCodigo: 'Mostre este código para quem vai entrar no grupo',
  },
  hoje: {
    titulo: 'Hoje',
    vazio: 'Nenhum registro hoje. Bora beber água. 💧',
    voce: 'Você',
    alguem: 'Alguém',
    registrosDeHoje: 'Registros de hoje',
    empate: 'Empate técnico',
    voceNaFrente: (volume: string) => `Você está ${volume} na frente`,
    parceiroNaFrente: (nome: string, volume: string) => `${nome} está ${volume} na frente`,
    abrirPerfil: 'Abrir perfil',
  },
  nav: {
    hoje: 'Hoje',
    ranking: 'Ranking',
    historico: 'Histórico',
    perfil: 'Perfil',
    registrarAgua: 'Registrar água',
  },
  ranking: {
    titulo: 'Ranking',
    periodo: 'Período',
    periodos: { day: 'Hoje', week: 'Semana', month: 'Mês', all: 'Total' },
    hoje: 'Hoje',
    ontem: 'Ontem',
    semanaDe: (intervalo: string) => `Semana de ${intervalo}`,
    desde: (data: string) => `Desde ${data}`,
    anterior: 'Período anterior',
    proximo: 'Próximo período',
    nadaRegistrado: 'Nada registrado neste período',
    mediasERecordes: 'Médias e recordes',
    mediaPorDia: 'Média por dia',
    melhorDia: 'Melhor dia',
    diasRegistrados: 'Dias registrados',
    registros: 'Registros',
    de: (a: number, b: number) => `${a} de ${b}`,
    semDados: '—',
    encerrado: (mes: string, resultado: string) => `${mes} encerrado — ${resultado}`,
    venceu: (nome: string) => `${nome} venceu 🏆`,
    empate: 'Empate',
    versus: ' × ',
    fechar: 'Fechar',
  },
  historico: {
    titulo: 'Histórico',
    membro: 'Membro',
    mesAnterior: 'Mês anterior',
    proximoMes: 'Próximo mês',
    diasSemana: ['S', 'T', 'Q', 'Q', 'S', 'S', 'D'],
    nenhumRegistro: 'Nenhum registro neste dia',
    rodape: (mes: string, total: string, media: string, dias: string) =>
      `${mes}: ${total} · média ${media}/dia · ${dias} dias`,
  },
  perfil: {
    titulo: 'Perfil',
    nome: 'Nome',
    salvar: 'Salvar',
    cor: 'Cor',
    cores: {
      blue: 'Azul',
      green: 'Verde',
      yellow: 'Amarelo',
      orange: 'Laranja',
      purple: 'Roxo',
      pink: 'Rosa',
    },
    grupo: 'Grupo',
    membros: 'Membros',
    sairMesmo: 'Sair mesmo?',
  },
  garrafas: {
    titulo: 'Minhas garrafas',
    adicionar: 'Adicionar garrafa',
    novaGarrafa: '+ nova garrafa',
    nome: 'Nome da garrafa',
    volume: 'Volume (ml)',
    emoji: 'Emoji (opcional)',
    salvar: 'Salvar',
    arquivar: 'Arquivar',
    arquivarMesmo: 'Arquivar mesmo?',
    nomeInvalido: 'Use de 1 a 30 caracteres',
    volumeInvalido: 'Volume entre 1 e 10.000 ml',
    vazio: 'Nenhuma garrafa ainda. Adicione a primeira.',
  },
  erro: {
    abaQuebrou: 'Algo quebrou nesta aba',
    recarregar: 'Recarregar',
    semConexao: 'Sem conexão',
    generico: 'Algo deu errado. Tente de novo.',
  },
  registros: {
    editar: 'Editar',
    excluir: 'Excluir',
    excluirMesmo: 'Excluir mesmo?',
    fotoDoRegistro: 'Foto do registro',
  },
  registrar: {
    minhasGarrafas: 'Minhas garrafas',
    menosUm: (nome: string) => `${nome} menos um`,
    valorAvulso: 'Valor avulso',
    registrar: (volume: string) => `Registrar ${volume}`,
    registrarVazio: 'Registrar',
    salvarAlteracoes: 'Salvar alterações',
    foto: '📷 foto',
    nota: '📝 nota',
    agora: '🕐 agora',
    fotoErro: 'Não foi possível usar essa imagem.',
    removerFoto: 'Remover foto',
    fechar: 'Fechar',
  },
  sync: {
    pendente: 'Aguardando envio',
    falhaTentarNovamente: 'Falha ao enviar — tentar novamente',
    desatualizado: 'Dados desatualizados',
  },
} as const
