export const STRINGS = {
  app: { nome: 'GymFishes' },
  auth: {
    entrar: 'Entrar',
    criarConta: 'Criar conta',
    email: 'E-mail',
    senha: 'Senha',
    emailInvalido: 'E-mail inválido',
    senhaCurta: 'A senha precisa de pelo menos 8 caracteres',
    credenciaisInvalidas: 'E-mail ou senha incorretos',
    jaTenhoConta: 'Já tenho conta',
    naoTenhoConta: 'Ainda não tenho conta',
    sair: 'Sair',
  },
  onboarding: {
    tituloNome: 'Como você quer aparecer?',
    campoNome: 'Seu nome',
    nomeCurto: 'Use pelo menos 2 caracteres',
    nomeLongo: 'Use no máximo 20 caracteres',
    tituloGrupo: 'Vocês competem em grupo',
    criarGrupo: 'Criar grupo',
    entrarComCodigo: 'Entrar com código',
    campoGrupo: 'Nome do grupo',
    campoCodigo: 'Código do convite',
    codigoInvalido: 'Código inválido',
    continuar: 'Continuar',
  },
  grupo: {
    codigoDoConvite: 'Código do convite',
    codigoFalhou: 'Não foi possível gerar um código. Tente de novo.',
  },
  hoje: {
    titulo: 'Hoje',
    vazio: 'Nenhum registro hoje. Bora beber água. 💧',
  },
  nav: {
    hoje: 'Hoje',
    registrarAgua: 'Registrar água',
  },
  erro: {
    abaQuebrou: 'Algo quebrou nesta aba',
    recarregar: 'Recarregar',
    semConexao: 'Sem conexão',
    generico: 'Algo deu errado. Tente de novo.',
  },
} as const
