export const STRINGS = {
  app: { nome: 'GymFishes' },
  auth: {
    entrar: 'Entrar',
    criarConta: 'Criar conta',
    email: 'E-mail',
    senha: 'Senha',
    emailInvalido: 'E-mail inválido',
    senhaCurta: 'A senha precisa de pelo menos 8 caracteres',
    credenciaisInvalidas: 'E-mail ou senha incorretos',
    jaTenhoConta: 'Já tenho conta',
    naoTenhoConta: 'Ainda não tenho conta',
    sair: 'Sair',
  },
  onboarding: {
    tituloNome: 'Como você quer aparecer?',
    campoNome: 'Seu nome',
    nomeCurto: 'Use pelo menos 2 caracteres',
    nomeLongo: 'Use no máximo 20 caracteres',
    tituloGrupo: 'Vocês competem em grupo',
    criarGrupo: 'Criar grupo',
    entrarComCodigo: 'Entrar com código',
    campoGrupo: 'Nome do grupo',
    campoCodigo: 'Código do convite',
    codigoInvalido: 'Código inválido',
    continuar: 'Continuar',
  },
  grupo: {
    codigoDoConvite: 'Código do convite',
    codigoFalhou: 'Não foi possível gerar um código. Tente de novo.',
    copiarCodigo: 'Copiar código',
    copiado: 'Copiado!',
    mostreEsteCodigo: 'Mostre este código para quem vai entrar no grupo',
  },
  hoje: {
    titulo: 'Hoje',
    vazio: 'Nenhum registro hoje. Bora beber água. 💧',
  },
  nav: {
    hoje: 'Hoje',
    perfil: 'Perfil',
    registrarAgua: 'Registrar água',
  },
  perfil: {
    titulo: 'Perfil',
    nome: 'Nome',
    salvar: 'Salvar',
    cor: 'Cor',
    cores: {
      blue: 'Azul',
      green: 'Verde',
      yellow: 'Amarelo',
      orange: 'Laranja',
      purple: 'Roxo',
      pink: 'Rosa',
    },
    grupo: 'Grupo',
    membros: 'Membros',
    sairMesmo: 'Sair mesmo?',
  },
  garrafas: {
    titulo: 'Minhas garrafas',
    adicionar: 'Adicionar garrafa',
    novaGarrafa: '+ nova garrafa',
    nome: 'Nome da garrafa',
    volume: 'Volume (ml)',
    emoji: 'Emoji (opcional)',
    salvar: 'Salvar',
    arquivar: 'Arquivar',
    arquivarMesmo: 'Arquivar mesmo?',
    nomeInvalido: 'Use de 1 a 30 caracteres',
    volumeInvalido: 'Volume entre 1 e 10.000 ml',
    vazio: 'Nenhuma garrafa ainda. Adicione a primeira.',
  },
  erro: {
    abaQuebrou: 'Algo quebrou nesta aba',
    recarregar: 'Recarregar',
    semConexao: 'Sem conexão',
    generico: 'Algo deu errado. Tente de novo.',
  },
} as const
